[package]
name = "sonos"
version = "0.1.0"
authors = []
edition = "2021"

[dependencies]
reqwest = { version = "0.12.23", features = ["blocking"] }
serde = { version = "1.0", features = ["derive"] }
quick-xml = { version = "0.36", features = ["serialize"] }
uuid = { version = "1.0", features = ["v4"] }
thiserror = "1.0"
warp = "0.3"
tokio = { version = "1.0", features = ["full"] }
bytes = "1.0"
log = "0.4"

# Custom test configurations
[[test]]
name = "discovery"
path = "tests/discovery.rs"

[[test]]
name = "soap"  
path = "tests/soap.rs"

[[test]]
name = "event_stream"
path = "tests/event_stream.rs"

# Examples
[[example]]
name = "state-monitor"
path = "examples/state-monitor.rs"
